In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


##3.3.2 LSTM Layers

In [1]:
import numpy as np

input_array = np.random.random([2, 3, 4]).astype(np.float32)

print("input_array.shape : ", input_array.shape)
print(input_array)

input_array.shape :  (2, 3, 4)
[[[8.0263347e-04 9.4372213e-01 8.7200993e-01 2.3643102e-01]
  [1.7941423e-01 4.6278557e-01 3.3241805e-01 1.9891573e-01]
  [2.3179723e-01 5.1212913e-01 3.6509234e-01 5.5243067e-02]]

 [[1.7301300e-01 3.9184740e-01 2.5182061e-03 4.9297124e-01]
  [1.1936936e-01 5.6260592e-01 7.8980035e-01 9.2139703e-01]
  [7.0331901e-01 7.8068835e-01 3.1546751e-01 4.5903978e-01]]]


In [2]:
from tensorflow.keras.layers import LSTM

lstm = LSTM(units=5)
output = lstm(inputs=input_array)

print("output.shape : ", output.shape)
print(output)

output.shape :  (2, 5)
tf.Tensor(
[[0.00575863 0.01938148 0.16121095 0.07808485 0.06796177]
 [0.07309169 0.06225979 0.2882294  0.09615558 0.15489003]], shape=(2, 5), dtype=float32)


In [3]:
from tensorflow.keras.layers import LSTM

lstm = LSTM(4, return_sequences=True, return_state=True)
timesteps_sequence_output, final_memory_state, final_carry_state = lstm(input_array)

print(timesteps_sequence_output.shape)
print(final_memory_state.shape)
print(final_carry_state.shape)

(2, 3, 4)
(2, 4)
(2, 4)


In [4]:
print(timesteps_sequence_output)

tf.Tensor(
[[[ 0.03608265  0.08261725 -0.06673047  0.06779353]
  [ 0.0588785   0.12548979 -0.04353924  0.11567029]
  [ 0.09934521  0.1558562  -0.02812583  0.15306598]]

 [[ 0.01368581  0.05557637  0.07032639  0.08940762]
  [-0.01273628  0.09255975  0.06884971  0.17867298]
  [ 0.08373731  0.17697956  0.16884731  0.2947619 ]]], shape=(2, 3, 4), dtype=float32)


In [5]:
print(final_memory_state)

tf.Tensor(
[[ 0.09934521  0.1558562  -0.02812583  0.15306598]
 [ 0.08373731  0.17697956  0.16884731  0.2947619 ]], shape=(2, 4), dtype=float32)


In [6]:
print(final_carry_state)

tf.Tensor(
[[ 0.16436908  0.33424604 -0.05894659  0.28016573]
 [ 0.13217935  0.411474    0.4043144   0.52821684]], shape=(2, 4), dtype=float32)
