In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 3.3.3 GRU Layers

In [1]:
import numpy as np

input_array = np.random.random([2, 3, 4]).astype(np.float32)

print("input_array.shape : ", input_array.shape)
print(input_array)

input_array.shape :  (2, 3, 4)
[[[0.2073067  0.3063313  0.0434818  0.44137028]
  [0.69142735 0.2747306  0.5983135  0.8334473 ]
  [0.28704536 0.50911176 0.02882786 0.36868766]]

 [[0.3983289  0.284512   0.7675     0.54895765]
  [0.1811587  0.7724002  0.0117892  0.43326816]
  [0.62970245 0.68615603 0.25699612 0.35497764]]]


In [2]:
from tensorflow.keras.layers import GRU

gru = GRU(units=5)

output = gru(input_array)
print(output.shape)

(2, 5)


In [3]:
from tensorflow.keras.layers import GRU

gru = GRU(units=5, return_sequences=True, return_state=True)
timesteps_sequence_output, final_state = gru(input_array)

print(timesteps_sequence_output.shape)
print(final_state.shape)

(2, 3, 5)
(2, 5)


In [4]:
print(timesteps_sequence_output)

tf.Tensor(
[[[ 0.01891758 -0.04872166  0.06609405 -0.17938267 -0.07831243]
  [-0.02576648 -0.00129194  0.20103242 -0.32097787 -0.13298412]
  [ 0.11724604 -0.07562219  0.21037123 -0.321966   -0.10787433]]

 [[-0.07022297  0.10615335  0.18192756 -0.11134841  0.02503316]
  [ 0.11402763 -0.03888989  0.2261088  -0.2828559  -0.0407371 ]
  [ 0.21892005 -0.13020581  0.3126161  -0.31912556 -0.03991474]]], shape=(2, 3, 5), dtype=float32)


In [5]:
print(final_state)

tf.Tensor(
[[ 0.11724604 -0.07562219  0.21037123 -0.321966   -0.10787433]
 [ 0.21892005 -0.13020581  0.3126161  -0.31912556 -0.03991474]], shape=(2, 5), dtype=float32)
