In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 3.3.4 Embedding Layer

In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential, layers
from tensorflow.keras.layers import Embedding

import numpy as np

input_array = np.random.randint(low=1, high=5, size=(2, 4))

print("input_array.shape : ", input_array.shape)
print(input_array)

input_array.shape :  (2, 4)
[[3 2 3 1]
 [1 1 4 4]]


In [2]:
model = Sequential()
model.add(layers.Embedding(input_dim=5, 
                           output_dim=10, 
                           input_length=4))

model.compile(optimizer='adam', 
              loss='mse') 

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 10)             50        
                                                                 
Total params: 50
Trainable params: 50
Non-trainable params: 0
_________________________________________________________________


In [4]:
output_array = model.predict(input_array)

print(input_array)

print("output_array.shape : ", output_array.shape)
print("\n", output_array)

1/1 [==============================] - 0s 84ms/step
[[3 2 3 1]
 [1 1 4 4]]
output_array.shape :  (2, 4, 10)

 [[[-0.03528105 -0.01075876  0.02719182 -0.01009989 -0.02149212
    0.02802959 -0.04390087  0.01840608  0.03454162  0.01432193]
  [-0.04608327  0.0223207   0.03758906  0.03718055  0.01598486
   -0.03229789 -0.03239311  0.01183023 -0.00770953 -0.04405893]
  [-0.03528105 -0.01075876  0.02719182 -0.01009989 -0.02149212
    0.02802959 -0.04390087  0.01840608  0.03454162  0.01432193]
  [ 0.01493208  0.0059549   0.00290539 -0.04813054  0.00778504
   -0.00438452 -0.01497168 -0.0333475   0.04598976 -0.02926098]]

 [[ 0.01493208  0.0059549   0.00290539 -0.04813054  0.00778504
   -0.00438452 -0.01497168 -0.0333475   0.04598976 -0.02926098]
  [ 0.01493208  0.0059549   0.00290539 -0.04813054  0.00778504
   -0.00438452 -0.01497168 -0.0333475   0.04598976 -0.02926098]
  [-0.00984681  0.04779139 -0.02078139 -0.03990106 -0.01244291
   -0.01486102  0.03883665  0.029228   -0.01935761  0.04254873]