In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 2.2.1 데이터 자료형

In [ ]:
import tensorflow as tf

vector_float64 = tf.constant([183, 89, 26.58], dtype=tf.float64)

print(vector_float64)

tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float64)


In [ ]:
import tensorflow as tf

vector_float32 = tf.cast(vector_float64, dtype=tf.float32)
vector_float16 = tf.cast(vector_float32, dtype=tf.float16)

vector_uint8 = tf.cast(vector_float64, dtype=tf.uint8)

print(vector_float32)
print(vector_float16)
print(vector_uint8)

tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float32)
tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float16)
tf.Tensor([183  89  26], shape=(3,), dtype=uint8)


In [ ]:
import numpy as np

vector_float64 = np.array([183, 89, 26.58], dtype=np.float64)
vector_float32 = vector_float64.astype('float32')
vector_float16 = vector_float64.astype('float16')

vector_uint8 = vector_float64.astype('uint8')

print(vector_float64, vector_float64.dtype, type(vector_float64))
print(vector_float32, vector_float32.dtype, type(vector_float64))
print(vector_float16, vector_float16.dtype, type(vector_float64))
print(vector_uint8, vector_uint8.dtype, type(vector_float64))

[183.    89.    26.58] float64 <class 'numpy.ndarray'>
[183.    89.    26.58] float32 <class 'numpy.ndarray'>
[183.    89.    26.58] float16 <class 'numpy.ndarray'>
[183  89  26] uint8 <class 'numpy.ndarray'>
