In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 2.2.2 데이터 형상 변경

In [ ]:
import numpy as np

array = np.arange(10)

print(array)
print('array.ndim : ', array.ndim)
print('array.shape : ', array.shape)

[0 1 2 3 4 5 6 7 8 9]
array.ndim :  1
array.shape :  (10,)


In [ ]:
array_25 = np.reshape(array, (2,5))
array_52 = np.reshape(array, (5,2))

print(array_25)
print('array_25.ndim :', array_25.ndim)
print('array_25.shape :', array_25.shape)

print('\n')
print(array_52, array_52.ndim, array_52.shape)
print('array_52.ndim :', array_52.ndim)
print('array_52.shape :', array_52.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array_25.ndim : 2
array_25.shape : (2, 5)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 2 (5, 2)
array_52.ndim : 2
array_52.shape : (5, 2)


In [ ]:
import numpy as np

# arange(0, 24, 1)
array = np.arange(0, 24, 1)

print(array)
print('\narray.ndim :', array.ndim)
print('array.shape :', array.shape)

# reshape(4,3,2)
array = array.reshape(4,3,2)

print('\n', array)
print('\narray.ndim :', array.ndim)
print('array.shape :', array.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

array.ndim : 1
array.shape : (24,)

 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

array.ndim : 3
array.shape : (4, 3, 2)


In [ ]:
import numpy as np

array = np.zeros((5, 5))
array[:,2] = 255

print(array, array.shape)

[[  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]] (5, 5)


In [ ]:
array.reshape(-1)

array([  0.,   0., 255.,   0.,   0.,   0.,   0., 255.,   0.,   0.,   0.,
         0., 255.,   0.,   0.,   0.,   0., 255.,   0.,   0.,   0.,   0.,
       255.,   0.,   0.])

In [ ]:
print( 'array.flatten()\n', array.flatten() )
print( '\narray.ravel()\n', array.ravel() )

array.flatten()
 [  0.   0. 255.   0.   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.
   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.   0.]

array.ravel()
 [  0.   0. 255.   0.   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.
   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.   0.]
