In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 3.3.1 SimpleRNN 층

In [1]:
import numpy as np

input_array = np.random.random([2, 3, 4]).astype(np.float32)

print("input_array.shape : ", input_array.shape)
print(input_array)

input_array.shape :  (2, 3, 4)
[[[0.6599483  0.20526344 0.3240818  0.09476294]
  [0.05105722 0.077159   0.2431317  0.74946254]
  [0.6673137  0.8841408  0.51599526 0.42315614]]

 [[0.8932028  0.6337807  0.13609654 0.8660492 ]
  [0.1471701  0.4040147  0.41725153 0.09215002]
  [0.7251835  0.8970765  0.57998705 0.9044475 ]]]


In [2]:
from tensorflow.keras.layers import SimpleRNN

simple_rnn = SimpleRNN(units=5)
output = simple_rnn(inputs=input_array)

print("output.shape : ", output.shape)
print("\n", output)

output.shape :  (2, 5)

 tf.Tensor(
[[-0.29854614 -0.21821766  0.75200677  0.3225288   0.18903129]
 [ 0.39519063 -0.93264914  0.40879333  0.24330822 -0.62885284]], shape=(2, 5), dtype=float32)


In [3]:
from tensorflow.keras.layers import SimpleRNN

simple_rnn = SimpleRNN(units=5, return_sequences=True, return_state=True)
timesteps_sequence_output, final_state = simple_rnn(input_array)

print("timesteps_sequence_output.shape : ", timesteps_sequence_output.shape)
print("final_state.shape : ", final_state.shape)

timesteps_sequence_output.shape :  (2, 3, 5)
final_state.shape :  (2, 5)


In [4]:
print(timesteps_sequence_output)

tf.Tensor(
[[[ 0.3136244   0.4735037  -0.31978092 -0.34831235 -0.29101053]
  [ 0.32846484  0.48524314 -0.11783468  0.21182382 -0.20449896]
  [ 0.3234522   0.82323515 -0.6970562  -0.25995696 -0.7191358 ]]

 [[ 0.6725534   0.72572625 -0.54851204 -0.6473465  -0.79375714]
  [-0.03857598  0.800966   -0.7025353   0.12665184  0.54238105]
  [ 0.90706897  0.8717331  -0.43586528  0.02494062 -0.8884886 ]]], shape=(2, 3, 5), dtype=float32)


In [5]:
print(final_state)

tf.Tensor(
[[ 0.3234522   0.82323515 -0.6970562  -0.25995696 -0.7191358 ]
 [ 0.90706897  0.8717331  -0.43586528  0.02494062 -0.8884886 ]], shape=(2, 5), dtype=float32)
