In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 3.2.3 배열 구조 변경

In [ ]:
import numpy as np

array = np.arange(10).reshape(2, 5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array = np.arange(10).reshape(2, 5)

print('array.shape :', array.shape)
print('array.ndim :', array.ndim)
print('array.dtype.name :', array.dtype.name)
print('array.size :', array.size)
print('array type :', type(array))

array.shape : (2, 5)
array.ndim : 2
array.dtype.name : int64
array.size : 10
array type : <class 'numpy.ndarray'>


In [ ]:
a = np.arange(10)                   
print('1d array \n', a)

b = np.arange(10).reshape(2, 5)     
print('2d array \n', b)

c = np.arange(30).reshape(3, 2, 5)
print('3d array \n', c)

1d array 
 [0 1 2 3 4 5 6 7 8 9]
2d array 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
3d array 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
array = np.arange(10).reshape(5, 2)
print('array', array)

# numpy.ravel(a, order='C')
print('\narray.ravel() \n', array.ravel())

array [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

array.ravel() 
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array = np.arange(10).reshape(5, 2)

print(array)
print('\nreturns the array, transposed\n', array.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

returns the array, transposed
 [[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
array = np.arange(10).reshape(5, 2)
print(array)

array.resize(2, 5)
print('\narray resize (2, 5)\n', array)

array.resize(1, 10)
print('\narray resize (1, 10)\n', array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

array resize (2, 5)
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array resize (1, 10)
 [[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
# 1차원 배열
array_1d = np.arange(6)
print('array :', array_1d)

print('\narray_1d.sum(axis=0)\n',           array_1d.sum(axis=0))

# 2차원 배열
array_2d = np.arange(6).reshape(2, 3)
print('array :', array_2d)

print('\narray_2d.sum(axis=0)\n',           array_2d.sum(axis=0))
print('array_2d.min(axis=1)\n',             array_2d.min(axis=1))

array : [0 1 2 3 4 5]

array_1d.sum(axis=0)
 15
array : [[0 1 2]
 [3 4 5]]

array_2d.sum(axis=0)
 [3 5 7]
array_2d.min(axis=1)
 [0 3]


## 3.2.4 배열 결합 및 분리하기

In [ ]:
a = np.array((1,2,3))
b = np.array((4,5,6))
c = np.hstack((a,b))
d = np.vstack((a,b))

print('a :\n', a)
print('b :\n', b)
print('\n np.hstack((a,b)) :\n', c)
print('\n np.vstack((a,b)) :\n', d)

a :
 [1 2 3]
b :
 [4 5 6]

 np.hstack((a,b)) :
 [1 2 3 4 5 6]

 np.vstack((a,b)) :
 [[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
c = np.hstack((a,b))
d = np.vstack((a,b))

print('a :\n', a)
print('b :\n', b)
print('\n np.hstack((a,b)) :\n', c)
print('\n np.vstack((a,b)) :\n', d)

a :
 [[1]
 [2]
 [3]]
b :
 [[4]
 [5]
 [6]]

 np.hstack((a,b)) :
 [[1 4]
 [2 5]
 [3 6]]

 np.vstack((a,b)) :
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
a = np.arange(12).reshape(2, 6)
b = np.hsplit(a, 2)
c = np.vsplit(a, 2)

print('np.arange(12).reshape(2, 6) :\n', a)
print('\n np.hsplit(array, 2) :\n', b)
print('\n np.vsplit(array, 2) :\n', c)

np.arange(12).reshape(2, 6) :
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 np.hsplit(array, 2) :
 [array([[0, 1, 2],
       [6, 7, 8]]), array([[ 3,  4,  5],
       [ 9, 10, 11]])]

 np.vsplit(array, 2) :
 [array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]


## 3.2.5 배열 복사

In [ ]:
a = np.arange(1, 10)
b = a

print(a)
print(b)

b[0] = 10

print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10  2  3  4  5  6  7  8  9]
[10  2  3  4  5  6  7  8  9]


In [ ]:
a = np.arange(1, 10)
c = a.copy()

print(a)
print(c)

c[0] = 10

print('\n', a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

 [1 2 3 4 5 6 7 8 9]
[10  2  3  4  5  6  7  8  9]


## 3.2.6 넘파이 범용 함수들

In [ ]:
array = np.arange(3)
print('array :', array)

print(np.exp(array))
print(np.sqrt(array))

array : [0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


## 3.2.7 인덱싱, 슬라이싱 및 반복

In [ ]:
array = np.arange(10)

print('array :', array)
print('\narray[1] : ', array[1])
print('array[-1] : ', array[-1])

print('\nrray[1:5] : ', array[1:5])
print('array[5:-1] : ', array[5:-1])

print('\narray[5:] : ', array[5:])
print('array[:5] : ', array[:5])

print('\narray[::2] : ', array[::2])
print('array[::-1] : ', array[::-1])

array : [0 1 2 3 4 5 6 7 8 9]

array[1] :  1
array[-1] :  9

rray[1:5] :  [1 2 3 4]
array[5:-1] :  [5 6 7 8]

array[5:] :  [5 6 7 8 9]
array[:5] :  [0 1 2 3 4]

array[::2] :  [0 2 4 6 8]
array[::-1] :  [9 8 7 6 5 4 3 2 1 0]


In [ ]:
array = np.arange(10).reshape(2, 5)

for row in array:
    print(row)

for element in array.flat:
    print(element)

[0 1 2 3 4]
[5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9
