In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 2.1.3 행렬

In [ ]:
import tensorflow as tf

matrix = tf.constant([
 [182, 99, 29.89],
 [183, 89, 26.58]])

print(matrix)

tf.Tensor(
[[182.    99.    29.89]
 [183.    89.    26.58]], shape=(2, 3), dtype=float32)


In [ ]:
matrix_numpy = matrix.numpy()

print(matrix_numpy)
type(matrix_numpy)

[[182.    99.    29.89]
 [183.    89.    26.58]]


numpy.ndarray