In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 2.3.2 슬라이싱

In [ ]:
import numpy as np

array_25 = np.reshape(np.arange(10), (2,5))
print(array_25)

print('\narray_25[:, 0] :', array_25[:, 0])
print('array_25[:, 1] :', array_25[:, 1])
print('array_25[:, -1] :', array_25[:, -1])

[[0 1 2 3 4]
 [5 6 7 8 9]]

array_25[:, 0] : [0 5]
array_25[:, 1] : [1 6]
array_25[:, -1] : [4 9]


In [ ]:
import numpy as np

array = np.arange(24)
array = array.reshape(2, 3, 4)

print('array.shape : ', array, array.shape)
print('\narray[0, 0, 0] :', array[0, 0, 0])
print('\narray[1, 2, 3] :', array[1, 2, 3])

array.shape :  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)

array[0, 0, 0] : 0

array[1, 2, 3] : 23


In [ ]:
print(array)

print('\narray[0, :, :] ', array[0, :, :], sep='\n')
print('array[-1, :, :] ', array[-1, :, :], sep='\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

array[0, :, :] 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array[-1, :, :] 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
print(array)

print('\narray[:, 0, :] ', array[:, 0, :], sep='\n')
print('array[:, -1, :] ', array[:, -1, :], sep='\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

array[:, 0, :] 
[[ 0  1  2  3]
 [12 13 14 15]]
array[:, -1, :] 
[[ 8  9 10 11]
 [20 21 22 23]]


In [ ]:
print(array)

print('\narray[:, :, 0] ', array[:, :, 0], sep='\n')
print('array[:, :, -1] ', array[:, :, -1], sep='\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

array[:, :, 0] 
[[ 0  4  8]
 [12 16 20]]
array[:, :, -1] 
[[ 3  7 11]
 [15 19 23]]


In [ ]:
print('array[1, 2, 3] ', array[1, 2, 3], sep='\n')

print('\narray[1, 2, :] ', array[1, 2, :], sep='\n')
print('\narray[1, :, 3] ', array[1, :, 3], sep='\n')
print('\narray[1, 2, :] ', array[:, 2, 3], sep='\n')

array[1, 2, 3] 
23

array[1, 2, :] 
[20 21 22 23]

array[1, :, 3] 
[15 19 23]

array[1, 2, :] 
[11 23]
