In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 2.4.1 데이터 연산자

In [ ]:
import numpy as np

vector_a = np.arange(1,3)
vector_b = np.arange(3,5)

print('vector_a :', vector_a)
print('vector_b :', vector_b)

vector_a : [1 2]
vector_b : [3 4]


In [ ]:
# 사칙연산 덧셈
print( vector_b + vector_a )

print( np.add(vector_b, vector_a) )

[4 6]
[4 6]


In [ ]:
# 사칙연산 빨셈
print( vector_b - vector_a )

print( np.subtract(vector_b, vector_a) )

[2 2]
[2 2]


In [ ]:
# 사칙연산 곱셈
print( vector_b * vector_a )

print( np.multiply(vector_b, vector_a) )

[3 8]
[3 8]


In [ ]:
# 사칙연산 나눗셈
print( vector_b / vector_a )

print( np.divide(vector_b, vector_a) )

[3. 2.]
[3. 2.]


In [ ]:
import numpy as np

matrix_a = np.arange(1,5).reshape(2,2)
matrix_b = np.arange(5,9).reshape(2,2)

print('matrix_a :', matrix_a, sep='\n')
print('matrix_b :', matrix_b, sep='\n')

matrix_a :
[[1 2]
 [3 4]]
matrix_b :
[[5 6]
 [7 8]]


In [ ]:
# 사칙연산 (+)
print( 'matrix.add() : ', np.add(matrix_b, matrix_a) ,sep='\n' )

# 사칙연산 (-)
print( '\nmatrix.subtract() : ', np.subtract(matrix_b, matrix_a) ,sep='\n' )

# 사칙연산 (*)
print( '\nmatrix.multiply() : ', np.multiply(matrix_b, matrix_a) ,sep='\n' )

# 사칙연산 (/)
print( '\nmatrix.divide() : ', np.divide(matrix_b, matrix_a) ,sep='\n' )

matrix.add() : 
[[ 6  8]
 [10 12]]

matrix.subtract() : 
[[4 4]
 [4 4]]

matrix.multiply() : 
[[ 5 12]
 [21 32]]

matrix.divide() : 
[[5.         3.        ]
 [2.33333333 2.        ]]


In [ ]:
import numpy as np

vector_a = np.arange(1, 10, 3)
vector_b = np.arange(1, 10, 4)

print('a :', vector_a)
print('b :', vector_b)

a : [1 4 7]
b : [1 5 9]


In [ ]:
print( 'a == b : ', vector_a == vector_b )
print( 'a < b :  ', vector_a < vector_b )
print( 'a > b :  ', vector_a > vector_b )

a == b :  [ True False False]
a < b :   [False  True  True]
a > b :   [False False False]


In [ ]:
import numpy as np 

vector_nan = np.empty((2, 2))

print( vector_nan )
print( np.isnan(vector_nan) )

[[5.         3.        ]
 [2.33333333 2.        ]]
[[False False]
 [False False]]


In [ ]:
vector_nan[:, 1] = np.nan

print( vector_nan )
print( np.isnan(vector_nan) )
print( np.isnan(vector_nan).sum() )

[[5.                nan]
 [2.33333333        nan]]
[[False  True]
 [False  True]]
2
