In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 2.4.2 행렬 곱

In [ ]:
import numpy as np

a = 1   # 스칼라
b = 2   # 스칼라

# 곱셉
print( np.multiply(a, b) )

# 행렬곱
print( np.dot(a, b) )

2
2


In [ ]:
import numpy as np

a = np.arange(1,3)  # 벡터
b = np.arange(1,3)  # 벡터

print(a)
print(b, '\n')

# 곱셉
print(np.multiply(a, b) )

# 행렬곱
print( np.dot(a, b) )

[1 2]
[1 2] 

[1 4]
5


In [ ]:
import numpy as np

a = np.arange(1,5).reshape(2,2) # 행렬
b = np.arange(1,5).reshape(2,2) # 행렬

print(a)
print(b, '\n')

# 곱셉
print( 'multiply', np.multiply(a, b), sep='\n')

# 행렬곱
print( '\n dot', np.dot(a, b), sep='\n')

[[1 2]
 [3 4]]
[[1 2]
 [3 4]] 

multiply
[[ 1  4]
 [ 9 16]]

 dot
[[ 7 10]
 [15 22]]
