In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# 넘파이

## 3.2.1 넘파이 설치하기

In [1]:
# conda 설치
# !conda install numpy

# pip 설치
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

np.__version__

'1.21.6'

## 3.2.2 기본적인 명령어

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

print('a.dtype :', a.dtype)
print('b.dtype :', b.dtype)

a.dtype : int64
b.dtype : float64


In [ ]:
array = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

print('array.shape :', array.shape)
print(array)

array.shape : (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.empty((2, 3))

array([[2.31036637e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array = np.arange(1, 10, 2)
array

array([1, 3, 5, 7, 9])

In [ ]:
a = np.array([5, 10, 15])
b = np.array([5])

c = a - b
c

array([ 0,  5, 10])

In [ ]:
a = np.array([5, 10, 15])
b = np.array([5])

c = a - b
print(c)

d = c < 5
print(d)

[ 0  5 10]
[ True False False]


In [ ]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[1, 2],
              [3, 4]])
# 아다마르곱
print('elementwise product       \n', a * b)
# 행렬곱셈
print('matrix product            \n', a @ b)
# 스칼라곱
print('dot product               \n', a.dot(b))

elementwise product       
 [[ 1  4]
 [ 9 16]]
matrix product            
 [[ 7 10]
 [15 22]]
dot product               
 [[ 7 10]
 [15 22]]
